version: '3.8'
services:
  angular-app:
    image: mohamedaminederouiche05/angular:latest
    ports:
      - "4201:80"  # Specify ports as strings
    restart: always  # Restart should be under the service





    