version: '3.8'
services:
  angular-app:
    image: mohamedaminederouiche05/angular:latest
    ports:
      - "4201:80"  # Specify ports as strings
    restart: always  # Restart should be under the service
  prometheus:
    image: prom/prometheus
    ports:
      - "9092:9090"  # Specify ports as strings
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - "3002:3000"  # Specify ports as strings
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - grafana_data:/var/lib/grafana
volumes:
  grafana_data:
  db:




    